-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 21:00:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`positions` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`qualifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`qualifications` (
  `qualification_id` INT NOT NULL AUTO_INCREMENT,
  `qualification_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`qualification_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`access_rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`access_rights` (
  `access_right_id` INT NOT NULL AUTO_INCREMENT,
  `access_right_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`access_right_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`workers` (
  `worker_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(13) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `position_id` INT NOT NULL,
  `qualification_id` INT NOT NULL,
  `access_right_id` INT NOT NULL,
  PRIMARY KEY (`worker_id`),
  INDEX `fk_workers_positions_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_workers_qualifications1_idx` (`qualification_id` ASC) VISIBLE,
  INDEX `fk_workers_access_rights1_idx` (`access_right_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_positions`
    FOREIGN KEY (`position_id`)
    REFERENCES `school`.`positions` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_qualifications1`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `school`.`qualifications` (`qualification_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_access_rights1`
    FOREIGN KEY (`access_right_id`)
    REFERENCES `school`.`access_rights` (`access_right_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`classes_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`classes_type` (
  `class_type_id` INT NOT NULL AUTO_INCREMENT,
  `type_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`class_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`classes_char`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`classes_char` (
  `class_char_id` INT NOT NULL AUTO_INCREMENT,
  `char_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`class_char_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`classes` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `class_type_id` INT NOT NULL,
  `classroom_teacher_worker_id` INT NOT NULL,
  `class_char_id` INT NOT NULL,
  PRIMARY KEY (`class_id`),
  INDEX `fk_classes_classes_type1_idx` (`class_type_id` ASC) VISIBLE,
  INDEX `fk_classes_workers1_idx` (`classroom_teacher_worker_id` ASC) VISIBLE,
  INDEX `fk_classes_classes_char1_idx` (`class_char_id` ASC) VISIBLE,
  CONSTRAINT `fk_classes_classes_type1`
    FOREIGN KEY (`class_type_id`)
    REFERENCES `school`.`classes_type` (`class_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_workers1`
    FOREIGN KEY (`classroom_teacher_worker_id`)
    REFERENCES `school`.`workers` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_classes_char1`
    FOREIGN KEY (`class_char_id`)
    REFERENCES `school`.`classes_char` (`class_char_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`students` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `class_id` INT NOT NULL,
  `access_right_id` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_students_access_rights1_idx` (`access_right_id` ASC) VISIBLE,
  INDEX `fk_students_classes1_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `school`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_access_rights1`
    FOREIGN KEY (`access_right_id`)
    REFERENCES `school`.`access_rights` (`access_right_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`lessons` (
  `lesson_id` INT NOT NULL AUTO_INCREMENT,
  `class_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  INDEX `fk_classes_has_subjects_subjects1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_classes_has_subjects_classes1_idx` (`class_id` ASC) VISIBLE,
  PRIMARY KEY (`lesson_id`),
  INDEX `fk_classes_has_subjects_workers1_idx` (`worker_id` ASC) VISIBLE,
  CONSTRAINT `fk_classes_has_subjects_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `school`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_subjects_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_subjects_workers1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `school`.`workers` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`schedules` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `class_subject_worker_id` INT NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedules_classes_has_subjects1_idx` (`class_subject_worker_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedules_classes_has_subjects1`
    FOREIGN KEY (`class_subject_worker_id`)
    REFERENCES `school`.`lessons` (`lesson_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
